name: iot_device_flutter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  influxdb_client:
    git:
      url: https://github.com/influxdata/influxdb-client-dart
      ref: main
  uuid: ^3.0.6
  sensors_plus: ^1.3.2
  battery_plus: ^2.1.4
  environment_sensors: ^0.2.0
  geolocator: ^8.2.1
  network_info_plus: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic
